In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [42]:
station = pd.read_csv('/home/kyohei/bike_share_data/201608_station_data.csv')

station_SF = station[station.landmark=='San Francisco'][['station_id','landmark']]

In [43]:
trip = pd.read_csv('/home/kyohei/bike_share_data/201608_trip_data.csv')

trip_SF = trip.merge(station_SF,left_on='Start Terminal',right_on='station_id',how='inner')

In [44]:
trip_SF['Start Date'] = trip_SF['Start Date'].apply(lambda x:pd.to_datetime(x))

trip_SF['dayofweek'] = trip_SF['Start Date'].apply(lambda x:x.dayofweek)

trip_SF_dayofweek = trip_SF[trip_SF['dayofweek']<=4]

In [47]:
trip_SF_dayofweek['start_hour'] = trip_SF_dayofweek['Start Date'].apply(lambda x:x.hour)

/home/kyohei/anaconda2/lib/python2.7/site-packages/ipykernel/__main__.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  if __name__ == '__main__':

In [76]:
trip_SF_dayofweek_AM = trip_SF_dayofweek[(trip_SF_dayofweek.start_hour>=7) & (trip_SF_dayofweek.start_hour<=9)]

start_end_group = pd.DataFrame(trip_SF_dayofweek_AM.groupby(['Start Terminal','End Terminal']).size()).reset_index()

start_end_group.rename(columns={0:'count'},inplace=True)

start_end_pivot = trip_SF_dayofweek_AM.pivot_table('Trip ID',index='Start Terminal',columns='End Terminal',aggfunc='count').fillna(0)

In [93]:
start_end_group.sort_values('count',ascending=False)

      Start Terminal  End Terminal  count
278               50            61   1770
884               70            50   1390
1035              74            61   1331
1034              74            60   1243
277               50            60   1209
862               69            67   1137
860               69            65   1133
848               69            51   1115
858               69            63   1111
1141              77            64   1099
885               70            51   1053
869               69            74   1042
847               69            50   1030
895               70            63    934
909               70            77    933
906               70            74    912
850               69            55    873
968               72            65    846
887               70            55    843
287               50            70    796
872               69            77    780
378               55            61    780
888               70            56    732
878               70            42    731
1138              77            61    712
725               65            69    707
25                39            69    682
281               50            64    638
899               70            67    627
852               69            57    626
...              ...           ...    ...
56                41            66      1
55                41            65      1
53                41            62      1
1070              75            62      1
101               45            41      1
1076              75            68      1
39                41            46      1
1089              76            42      1
1092              76            47      1
1100              76            58      1
1127              77            47      1
94                42            73      1
976               72            73      1
824               68            63      1
166               46            82      1
825               68            64      1
202               48            39      1
181               47            58      1
177               47            54      1
868               69            73      1
168               47            41      1
161               46            73      1
105               45            48      1
154               46            66      1
139               46            48      1
136               46            42      1
133               45            91      1
912               70            91      1
109               45            54      1
1207              91            91      1

[1208 rows x 3 columns]

In [90]:
start_end_pivot.ix[(start_end_pivot.index.isin([39,48,50,54,55,57,60,62,66,69,67,70,71,72,73,74,90,91])==False),[54,55,62,67,70,71,72,73]]

End Terminal       54     55     62    67     70    71    72    73
Start Terminal
41                5.0   15.0    1.0   3.0  186.0   5.0   1.0   4.0
42                3.0   13.0   13.0   6.0  124.0   2.0   7.0   1.0
45                1.0    3.0    2.0  13.0    6.0  13.0   7.0   2.0
46                6.0    6.0    4.0  13.0   41.0   2.0   7.0   1.0
47                1.0    4.0    7.0   6.0   20.0   6.0   5.0   4.0
49                6.0    5.0    5.0  92.0   87.0  11.0   1.0   0.0
51               33.0    5.0    4.0   2.0  363.0   3.0   2.0   1.0
56              108.0   64.0    7.0  15.0   98.0   2.0   3.0  15.0
58                0.0    4.0   36.0   7.0   54.0   3.0   3.0   4.0
59                0.0   16.0    1.0  95.0   39.0   1.0   1.0   3.0
61                5.0  242.0   64.0   1.0  465.0  11.0   5.0   1.0
63                2.0   23.0    3.0  41.0  274.0   3.0  17.0   1.0
64                4.0   32.0   12.0  87.0  311.0  41.0   0.0   0.0
65                6.0  130.0  195.0  69.0  118.0   4.0  37.0   2.0
68                1.0   10.0    2.0   3.0   85.0   1.0   4.0  45.0
75               15.0   76.0    1.0  21.0    7.0   6.0  42.0  28.0
76                3.0    0.0   19.0  52.0  231.0   3.0   8.0   6.0
77                1.0    9.0  403.0   7.0  155.0   1.0  11.0   8.0
82                2.0   17.0    2.0   5.0  301.0   4.0  17.0   0.0

In [94]:
trip_SF_dayofweek_PM = trip_SF_dayofweek[(trip_SF_dayofweek.start_hour>=16) & (trip_SF_dayofweek.start_hour<=19)]

start_end_pivot = trip_SF_dayofweek_PM.pivot_table('Trip ID',index='Start Terminal',columns='End Terminal',aggfunc='count').fillna(0)

In [97]:
start_end_pivot.ix[[46,50,54,55,58,59,61,68,70,71,72,73,77],[41,45,48,49,51,56,57,60,62,63,64,65,67,76,82]]

End Terminal,41,45,48,49,51,56,57,60,62,63,64,65,67,76,82
Start Terminal,,,,,,,,,,,,,,,
46,4.0,2.0,9.0,8.0,9.0,23.0,84.0,45.0,2.0,7.0,4.0,4.0,22.0,33.0,3.0
50,10.0,4.0,44.0,30.0,26.0,14.0,22.0,499.0,6.0,10.0,14.0,96.0,13.0,41.0,24.0
54,7.0,3.0,19.0,41.0,30.0,81.0,6.0,96.0,9.0,8.0,19.0,25.0,9.0,57.0,22.0
55,11.0,15.0,7.0,18.0,15.0,27.0,83.0,58.0,115.0,67.0,23.0,124.0,49.0,29.0,11.0
58,0.0,0.0,0.0,12.0,3.0,9.0,7.0,8.0,4.0,2.0,4.0,8.0,4.0,37.0,1.0
59,5.0,7.0,1.0,2.0,2.0,7.0,7.0,73.0,3.0,3.0,2.0,25.0,24.0,25.0,0.0
61,17.0,10.0,19.0,50.0,145.0,77.0,20.0,124.0,49.0,43.0,38.0,61.0,37.0,59.0,36.0
68,13.0,90.0,5.0,12.0,12.0,20.0,28.0,23.0,4.0,3.0,15.0,133.0,80.0,10.0,4.0
70,55.0,6.0,17.0,93.0,237.0,33.0,194.0,343.0,55.0,97.0,166.0,222.0,165.0,96.0,197.0
71,25.0,67.0,6.0,25.0,5.0,22.0,11.0,36.0,10.0,12.0,27.0,9.0,27.0,8.0,11.0
72,9.0,7.0,3.0,4.0,15.0,14.0,14.0,23.0,28.0,2.0,7.0,24.0,84.0,49.0,8.0
73,18.0,16.0,3.0,4.0,6.0,3.0,8.0,56.0,4.0,4.0,7.0,8.0,9.0,29.0,4.0
77,17.0,30.0,16.0,62.0,66.0,34.0,43.0,218.0,32.0,20.0,109.0,50.0,115.0,56.0,24.0